[package]
name = "rust-old-capnp"
version = "0.1.0"
edition = "2021"

[env]
OUT_DIR = "kluge"

[dependencies]
capnp = "0.20.1"
eyre = "0.6.12"
fuzz-models = { path = "../fuzz-models" }

[build-dependencies]
build-helper = { path = "../build-helper" }
