[package]
name = "recapn-bench"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.16", features = ["derive"] }
cpp-interop = { path = "../cpp-interop" }
rust-old-capnp = { path = "../rust-old-capnp" }
rust-recapn = { path = "../rust-recapn" }
