[package]
name = "fuzz-models"
version = "0.1.0"
edition = "2021"

[dependencies]
arbitrary = { version = "1", optional = true, features = ["derive"] }
strum = { version = "0.26.3", features = ["derive"] }

[lints]
workspace = true

[build-dependencies]
cbindgen = "0.27.0"
